apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: minecraft
  labels:
    {{- include "mc.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "mc.selectorLabels" . | nindent 6 }}
  ingress:
    - fromEndpoints:
        - matchLabels:
            {{- include "playit.selectorLabels" . | nindent 12 }}
      toPorts:
        - ports:
            - port: "25565"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              {{- include "mc.allowedFQDNEntries" . | trim | nindent 14 }}
    - toFQDNs:
        {{- include "mc.allowedFQDNEntries" . | trim | nindent 8 }}
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP