apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: playit
  labels:
    {{- include "playit.labels" . | nindent 4 }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "playit.selectorLabels" . | nindent 6 }}
  ingress: []
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchName: "playit.gg"
              - matchPattern: "*.playit.gg"
              - matchName: "ply.gg"
              - matchPattern: "*.ply.gg"
              - matchName: "playit.cloud"
              - matchPattern: "*.playit.cloud"
    - toEndpoints:
        - matchLabels:
            {{- include "mc.selectorLabels" . | nindent 12 }}
      toPorts:
        - ports:
            - port: "25565"
              protocol: TCP
    - toFQDNs:
        - matchName: "playit.gg"
        - matchPattern: "*.playit.gg"
        - matchName: "ply.gg"
        - matchPattern: "*.ply.gg"
        - matchName: "playit.cloud"
        - matchPattern: "*.playit.cloud"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toCIDRSet:
        {{- range .Files.Lines "files/playit-allowed-cidrs.txt" }}
        {{- if and . (not (hasPrefix "#" .)) }}
        - cidr: {{ . | quote }}
        {{- end }}
        {{- end }}