#!/usr/bin/env bash
# Fetches playit.gg's published IP ranges (github.com/playit-cloud/network,
# full/union list) into a CIDR file consumed by playit-networkpolicy.yaml.
#
# Fails loudly and leaves the existing output file untouched on any error —
# never silently narrows or blanks what playit's egress policy allows.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="${OUTPUT_FILE:-$REPO_ROOT/chart/files/playit-allowed-cidrs.txt}"
PLAYIT_IPS_URL="${PLAYIT_IPS_URL:-https://raw.githubusercontent.com/playit-cloud/network/main/ips.txt}"

log() { echo "[sync-playit-ips] $*" >&2; }

IPV4_CIDR_RE='^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'
IPV6_CIDR_RE='^[0-9A-Fa-f:]+/[0-9]{1,3}$'

fetched="$(curl -sfL "$PLAYIT_IPS_URL")" || {
  log "ERROR: failed to fetch $PLAYIT_IPS_URL"
  exit 1
}

if [ -z "$fetched" ]; then
  log "ERROR: fetched content is empty"
  exit 1
fi

line_count=0
while IFS= read -r line; do
  [ -z "$line" ] && continue
  line_count=$((line_count + 1))
  if ! [[ "$line" =~ $IPV4_CIDR_RE || "$line" =~ $IPV6_CIDR_RE ]]; then
    log "ERROR: line does not look like a CIDR block: $line"
    exit 1
  fi
done <<< "$fetched"

if [ "$line_count" -eq 0 ]; then
  log "ERROR: no CIDR lines found in fetched content"
  exit 1
fi

{
  echo "# Generated by scripts/sync-playit-ips.sh — do not edit by hand."
  echo "# Source: $PLAYIT_IPS_URL"
  echo "# Regenerate with: task playit:sync-ips"
  echo "$fetched"
} > "$OUTPUT_FILE"

log "Wrote $line_count CIDR block(s) to $OUTPUT_FILE"